export const shopDataReducerActionType = {
    FETCHING_START: "FETCHING_START",
    FETCH_COLLECTION_DATA_SUCCESS : "FETCH_COLLECTION_DATA_SUCCESS",
 
    FETCHING_Collection_DATA_FAILURE: "FETCHING_COLLECTION_DATA_FAILURE"

}