

export const SnackBarReducerActionType =  {
    ITEM_ADDED_TO_CART: "ITEM_ADDED_TO_CART",
    ITEM_REMOVED_FROM_CART : 'ITEM_REMOVED_FROM_CART',
    ITEM_ADDED_TO_WISHLIST : 'ITEM_ADDED_TO_WISHLIST',
    ITEM_REMOVED_FROM_WISHLIST :'ITEM_REMOVED_FROM_WISHLIST',
    HIDE_SNACKBAR: "HIDE_SNACKBAR",
    SHOW_SNACKBAR: "SHOW_SNACKBAR"
}
