export const CartReducerActionType = {
    Cart_TOGGLER : 'CART_TOGGLER',
    CART_SHOW : 'CART_SHOW',
    CART_HIDE : 'CART_HIDE',
    ADD_ITEMS : 'ADD_ITEMS',
    REMOVE_ITEM : 'REMOVE_ITEM',
    PAYMENT_SUCCESS : "PAYMENT_SUCCESS",
    SELECTED_ITEMS : "SELETED_ITEMS",
    INCREASE_QUANTITY: "INCREASE_QUANTITY",
    DECREASE_QUANTITY : 'DECREASE_QUANTITY',
    CHECK_ALL: "CHECK_ALL",
    UNCHECK_ALL: "UNCHECK_ALL",
    CHECK_ITEM: "CHECK_ITEM",
    UNCHECK_ITEM: "UNCHECK_ITEM",

}

